name: Frontend CI/CD - Develop

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build frontend (Vite)
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Deploy dist to OCI (temp directory)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          source: "dist/*"
          target: "/home/opc/frontend_tmp"
          strip_components: 1

      - name: Publish frontend to Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html_8081/*
            sudo cp -r /home/opc/frontend_tmp/* /var/www/html_8081/
            sudo chown -R nginx:nginx /var/www/html_8081
            sudo restorecon -Rv /var/www/html_8081
            sudo systemctl reload nginx
